displayName=Watchcat
author=graeme2277
support=https://github.com/graeme2277/watchcat
description=Protects your cat while fighting Hell-Rat Behemoths with health, food, and spice warnings
tags=cat,hellcat,hell-rat,behemoth,spice,stew,edgeville
plugins=com.graeme2277.watchcat.WatchcatPlugin
version=1.0.0
build=standard
